name: Deploy para AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Instalar Dependências
      run: pip install -r requirements.txt
      
    - name: Validar sintaxe do Python
      run: python -m py_compile lambda-anisio.py  # Substitua pelo nome do seu programa

    - name: Configurar credenciais da AWS
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Copiar para AWS S3
      run: aws s3 cp app.py s3://appanisio-aula6-prd/ --region us-east-1
